server:
  proxy:
    hostport: localhost:5432
  admin:
    hostport: localhost:10000
nodes:
  master:
    hostport: journeys-redshift-dev.ciocgeapvkql.us-east-1.redshift.amazonaws.com:5439
    role: master
    metadata:
      cpu: large
      disk: fast

healthcheck:
  delay: 60
  query: select now();

pool:
  capacity: 1

credentials:
  username: larry
  database: larry
  password: T4XY6b97scVZju
  options:
    application_name: crunchy-proxy
  ssl:
    enable: true
    sslmode: require
    sslcert: ./scripts/certs/client/client.crt
    sslkey: ./scripts/certs/client/client.key
    sslrootca: ./scripts/certs/client/ca.crt
    sslservercert: ./scripts/certs/server/server.crt
    sslserverkey: ./scripts/certs/server/server.key
    sslserverca: ./scripts/certs/server/ca.crt

